# Use root/example as user/password credentials

version: "3.1"
#docker run -d -p 5672:5672 rabbitmq
services:
  rabbitmq:
    image: rabbitmq:latest
    ports:
      - 5672:5672

  redis:
    image: redis:latest
    ports:
      - 6379:6379
